### ISSUE TITLE
Custom Sections issue with properties

### ISSUE THREAD

**Issue by newmans99** [stefanwalther/qliksense-extension-tutorial#1]
I have noticed that when I create a custom section and header that my custom properties don't get "initiated" until the user edits each of the properties. This causes problems since the property isn't available until the user edits everything. Prior to having a custom section (using settings), all of the properties populated automatically.

Is there a setting/command needed to be executed to instantiate the custom parameters?

**Comment by newmans99** [comment]
This can be closed, I re-wrote the section and it appears to be working correctly now. Unfortunately, I don't know how to delete the above "issue" so I will close it here. Thanks.

**Comment by stefanwalther** [comment]
Thx anyhow! Is the tutorial useful so far? Any general feedback?

**Comment by newmans99** [comment]
Really love it... Wished that the rest was there. Can't be done fast enough... :)

I really like the "proven" practice approach so that I can avoid the pitfalls that you have made/experienced. Hopefully I will be able to add content in the future.

BTW: The problem resurfaced, so there may be other issues. I will continue to research and figure out on my own and report back.

Thanks
