### ISSUE TITLE
Request: Using show-service-popup-dialog with custom properties

### ISSUE THREAD

**Issue by KFredberg** [stefanwalther/qliksense-extension-tutorial#13]
If it's possible and fairly easy to use the popup service Qlik Sense uses for adding dimensions/measures/data for your own custom properties I would like to read a tutorial on that topic.
This would be useful when you create a hypercube on the fly, now that arrays/list are supported.

**Comment by stefanwalther** [comment]
Unfortunately this is not supported nor documented right now. In this tutorial I'll try to stick only to officially documented API calls ... I hope you understand. Ask e.g. on the Qlik branch slack-channel.
