### ISSUE TITLE
Changes are not reflecting in Qliksense extension

### ISSUE THREAD

**Issue by nsurnar** [stefanwalther/qliksense-extension-tutorial#14]
Hi,

I followed every step mentioned.
But still every time I have to close the Qliksense desktop and start it again to see the changes.
How can I solve this issue? Is there any setting I missed ?
Please help me out on this.

Thanks, Nitin

**Comment by stefanwalther** [comment]
Hi,

see here, I have described it in detail:
https://github.com/stefanwalther/qliksense-extension-tutorial/blob/master/tutorial/part-09/1002-Troubleshooting-FAQ.md#changes-made-in-a-visualization-extension-are-not-reflected

Regards
Stefan

**Comment by stefanwalther** [comment]
Since this is a known issue and also documented as mentioned above, I'll close this.
