### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by alexbjorlig** [stefanwalther/qliksense-extension-tutorial#16]
Hi thanks for the tutorial. 

There is a broken link on this page: http://qliksite.io/tutorials/qliksense-visualization-extensions/part-01/02-Introduction-to-QlikSense-Visualization-Extensions/#
Regarding how to deploy visualizations in Qlik Sense Server.

**Comment by stefanwalther** [comment]
Thx a lot, will fix.

**Comment by stefanwalther** [comment]
This is the correct link: http://help.qlik.com/en-US/sense-developer/3.0/Subsystems/Extensions/Content/Howtos/deploy-extensions.htm
