### ISSUE TITLE
Cannot read property 'qInterColumnSortOrder' og undefined

### ISSUE THREAD

**Issue by alexbjorlig** [stefanwalther/qliksense-extension-tutorial#17]
Hi Stefan - Thanks for an awesome tutorial, enjoy the angular part. 

When I try to follow the example in the tutorial - the following error appears: qInterColumnSortOrder?

**Comment by stefanwalther** [comment]
Hi, thx for reporting the issue. Which chapter are you referring to?

**Comment by Shneior** [comment]
Hi
try this 
new line "qInterColumnSortOrder : [0,1]," in initialproperties.js

define( [], function () {
    'use strict';
    return {
        qHyperCubeDef: {
            qDimensions: [],
            qMeasures: [],
			qInterColumnSortOrder : [0,1],
            qInitialDataFetch: [
                {
                    qWidth: 10,
                    qHeight: 50
                }
            ]
        }
    };
} );
