### ISSUE TITLE
Missing closing brackets

### ISSUE THREAD

**Issue by Hartsner** [stefanwalther/qliksense-extension-tutorial#2]
https://github.com/stefanwalther/qliksense-extension-tutorial/blob/master/tutorial/part-01/09-Loading-Resources.md#2-adding-a-link-to-a-style-sheet-to-the-documents-header

define( [ 
        "jquery"
    ], function ( $ ) {

```
    $('<link rel="stylesheet" type="text/css" href="/extensions/my-extension/css/myStyle.css").appendTo("head");

} );
```

missing closing brackets >'
Should be:
define( [ 
        "jquery"
    ], function ( $ ) {

```
    $('<link rel="stylesheet" type="text/css" href="/extensions/my-extension/css/myStyle.css">').appendTo("head");

} );
```

**Comment by stefanwalther** [comment]
Thx, fixed.
