### ISSUE TITLE
Not able to insert dimensions and expression in Qliksense Heatmap

### ISSUE THREAD

**Issue by deepaktibhe** [stefanwalther/qliksense-extension-tutorial#21]
Hi 

We have developed our own qlik sense heatmap chart.
I am new to javascript.Could you please share how to insert our own dimensions and expressions in below code.

Thanks

**Comment by stefanwalther** [comment]
Sorry, I am not able to answer this question without further details. I recommend that you post your question to the branch slack channel: http://qlikbranch-slack-invite.herokuapp.com/
