### ISSUE TITLE
Typo on part-01/ 05-Improving-the-Hello-World-Experience Page

### ISSUE THREAD

**Issue by jpdp** [stefanwalther/qliksense-extension-tutorial#7]
There seems to be a small error in the part-01/05-Improving-the-Hello-World-Experience:
![image](https://cloud.githubusercontent.com/assets/11069710/10156820/c9c2620a-66c3-11e5-8772-f860e0342601.png)

Should be **myDynamicOutput**

**Comment by stefanwalther** [comment]
Thx a lot, will fix it ASAP.
